# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2025.0.5
_src_path: gh:WorldconVotingSystems/nomnom
advisory_votes: true
convention_name: Seattle Worldcon 2025
domain_name: seattlein2025.org
email_domain_name: seattlein2025.org
hugo_packet_enabled: false
project_slug: seattle-2025
use_development: false
