[project]
name = "seattle-2025"
version = "1.0.0"
description = "Convention app for Seattle Worldcon 2025"
authors = []
dependencies = [
"nomnom-hugoawards",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[tool.ruff.lint.isort]
known-first-party = ["seattle_2025"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
