# Generated by Django 5.1.3 on 2025-01-25 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seattle_2025_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="controllperson",
            index=models.Index(fields=["perid"], name="controll_person_perid_index"),
        ),
        migrations.AddIndex(
            model_name="controllperson",
            index=models.Index(
                fields=["newperid"], name="controll_person_newperid_index"
            ),
        ),
    ]
