name: "seattle-2025"
x-image: &image
  image: ghcr.io/worldconvotingsystems/seattle-2025:${NOMNOM_VERSION:-main}
x-boot: &boot
  depends_on:
    boot:
      condition: service_completed_successfully
x-redis: &redis
  NOM_REDIS_HOST: redis
  NOM_REDIS_PORT: 6379
x-db: &db
  NOM_DB_HOST: db
  NOM_DB_PORT: 5432
  NOM_DB_NAME: $NOM_DB_NAME
  NOM_DB_USER: $NOM_DB_USER
  NOM_DB_PASSWORD: $NOM_DB_PASSWORD

services:
  web:
    <<: [*image, *boot]
    volumes:
      - staticfiles:/staticfiles
    ports:
      - "127.0.0.1:8000:8000"
    command: bash /app/docker/start.sh server
    links:
      - db
      - redis
    env_file:
      - .env
    environment:
      NOM_STATIC_FILE_ROOT: /app/staticfiles
      <<: [*db, *redis]
    healthcheck:
      start_period: 30s
      start_interval: 2s
      interval: 30s
      timeout: 5s
      retries: 3
      test:
        [
          "CMD",
          "/bin/bash",
          "-c",
          "set -o pipefail; curl -s --fail -H 'Host: nomnom-staging.seattlein2025.org' http://localhost:8000/watchman/ | jq --exit-status '.databases[].default.ok == true' > /dev/null",
        ]

  worker:
    <<: [*image, *boot]
    command: /app/docker/start.sh worker
    links:
      - db
      - redis
    env_file:
      - .env
    environment:
      NOM_STATIC_FILE_ROOT: /app/staticfiles
      <<: [*db, *redis]

  boot:
    <<: *image
    command: /bin/bash /app/docker/start.sh bootstrap
    user: root
    environment:
      NOM_STATIC_FILE_ROOT: /staticfiles
      <<: [*db, *redis]
    env_file:
      - .env
    volumes:
      - staticfiles:/staticfiles
      - ".:/src"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
      - redis

  db:
    image: postgres:17.1
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      - POSTGRES_DB=${NOM_DB_NAME}
      - POSTGRES_USER=${NOM_DB_USER}
      - POSTGRES_PASSWORD=${NOM_DB_PASSWORD}
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready", "-d", "$NOM_DB_NAME", "-u", "$NOM_DB_USER"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  redis:
    image: redis:7
    ports:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "_ping"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 5s

volumes:
  db-data:
  staticfiles:
