name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: "41 14 * * *"
  push:
    branches:
      - "main"
      - "ci-*"
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io

jobs:
  prepare:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: set the build step environment
        run: |
          # what even the fuck is this.
          # here purely because of https://github.com/orgs/community/discussions/25768
          registry_image=$REGISTRY/${{ github.repository }}
          echo REGISTRY_IMAGE_LC="${registry_image,,}" >> "$GITHUB_ENV"

          # Default to allowing push
          echo "CAN_PUSH_IMAGES=true" >> "$GITHUB_ENV"

          # if we have a named ref (branch) use that, otherwise use the SHA
          if [[ ${{ github.ref }} == refs/heads/* ]]; then
             BRANCH_NAME=$(echo ${{ github.ref }} | sed 's#refs/heads/##')
             echo "REGISTRY_TAG=$BRANCH_NAME" >> "$GITHUB_ENV"
          else
             SHA=${{ github.sha }}
             echo "REGISTRY_TAG=$SHA" >> "$GITHUB_ENV"
          fi

      - name: Check for push image permissions
        # if this is a pull request from another repository, then disable pushing
        if: github.event.pull_request.head.repo.full_name != github.repository && github.event_name == 'pull_request'
        run: |
          echo "This is a pull request from an external repository. Disabling image push."
          echo "CAN_PUSH_IMAGES=false" >> "$GITHUB_ENV"

      - name: persist configuration
        id: persist
        run: |
          {
              echo "can_push_images=$CAN_PUSH_IMAGES"
              echo "registry_image=$REGISTRY_IMAGE_LC"
              echo "registry_tag=$REGISTRY_TAG"
          } >> "$GITHUB_OUTPUT"

    outputs:
      can_push_images: ${{ steps.persist.outputs.can_push_images }}
      registry_image: ${{ steps.persist.outputs.registry_image }}
      registry_tag: ${{ steps.persist.outputs.registry_tag }}

  build:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    env:
      CAN_PUSH_IMAGES: ${{ needs.prepare.outputs.can_push_images }}
      REGISTRY_IMAGE: ${{ needs.prepare.outputs.registry_image }}
      REGISTRY_TAG: ${{ needs.prepare.outputs.registry_tag }}
      PLATFORM: linux/amd64

    steps:
      - name: Set up the platform
        run: |
          # set the platform pair for later
          echo "PLATFORM_PAIR=${PLATFORM//\//-}" >> "$GITHUB_ENV"

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: env.CAN_PUSH_IMAGES == 'true'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push
        id: build
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          load: true # we need to load so we can save later for validation
          push: ${{ env.CAN_PUSH_IMAGES == 'true' }}
          # use the branch name as the tag, if we have it, otherwise use the SHA
          tags: "${{ env.REGISTRY_IMAGE }}:${{ env.REGISTRY_TAG }}"
          platforms: ${{ env.PLATFORM }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save Docker image for validation
        run: |
          image_id=${{ steps.load.outputs.imageid }}
          docker save "$image_id" -o /tmp/docker-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: docker-image
          path: /tmp/docker-image.tar
          retention-days: 3
    outputs:
      image_id: ${{steps.build.outputs.imageid}}
      tags: ${{ steps.meta.outputs.tags }}

  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    needs:
      - prepare
      - build

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: download the built image
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: docker-image
          path: /tmp

      - name: load the docker image
        run: |
          docker load -i /tmp/docker-image.tar
          docker tag ${{ needs.build.outputs.image_id }} ci:local

      - name: copy the environment
        run: |
          cp deploy/staging/.env.template deploy/staging/.env
          echo "NOMNOM_IMAGE=ci" >> deploy/staging/.env
          echo "NOMNOM_VERSION=local" >> deploy/staging/.env

      - name: show the compose configuration for debugging
        run: docker compose -f deploy/staging/compose.yml config

      - name: bootstrap the project
        run: docker compose -f deploy/staging/compose.yml up boot

      - name: start the staging environment
        run: |
          docker compose -f deploy/staging/compose.yml -p staging up --wait

      - name: attempt to read the home page from the website
        run: |
          curl -s -o /dev/null \
            -H Host:nomnom-staging.seattlein2025.org \
            -w "%{http_code}" \
            http://localhost:8000/ >> /tmp/status_code

      - name: check the status code
        run: |
          status_code=$(cat /tmp/status_code)
          if [ "$status_code" != "200" ]; then
            echo "The status code was not 200. It was $status_code."
            exit 1
          fi

  notify:
    runs-on: ubuntu-latest
    needs:
      - build
      - validate
    steps:
      - uses: umahmood/pushover-actions@5da31193f672e7418804bdb51836bdf20f393c8f # v1.1.0
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_API_KEY }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER_KEY }}
        with:
          status: ${{ job.status }}
          title: Seattle Image Updates
          message: |-
            The Seattle docker image has been updated: ${{ needs.build.outputs.tags }}
